name: ev_business_logic
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  bloc: ^8.1.1
  formz: ^0.4.0
  dio: ^5.2.0
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
